import type { ProposedTask } from '../types';

export const PROPOSED_TASKS: ProposedTask[] = [
  // Developer track
  {
    id: 'prop-dev-1',
    title: 'Solve 1 LeetCode / Algorithmic challenge (Tree / Graph)',
    category: 'Study',
    priority: 'high',
    notes: 'Focus on time & space complexity analysis. Write clean idiomatic solution.',
    estimatedPomodoros: 2,
    subtasks: [
      'Read problem & sketch example test cases',
      'Implement baseline solution',
      'Optimize edge cases and measure runtime',
    ],
    track: 'Developer',
    canBeHabit: true,
    habitFrequency: 'weekdays',
  },
  {
    id: 'prop-dev-2',
    title: 'Review 2 team Pull Requests & write constructive feedback',
    category: 'Work',
    priority: 'high',
    notes: 'Check for test coverage, type safety, performance pitfalls, and clean architecture.',
    estimatedPomodoros: 2,
    subtasks: [
      'Checkout branch and verify local build',
      'Inspect logic flow & unit test assertions',
      'Leave actionable and polite review comments',
    ],
    track: 'Developer',
    canBeHabit: false,
  },
  {
    id: 'prop-dev-3',
    title: 'Refactor legacy service & write comprehensive unit tests',
    category: 'Work',
    priority: 'medium',
    notes: 'Eliminate duplicate code, decouple dependencies, and boost test coverage to >85%.',
    estimatedPomodoros: 3,
    subtasks: [
      'Identify code smells and coupling points',
      'Write regression tests before modifying logic',
      'Refactor incrementally and run tests',
    ],
    track: 'Developer',
    canBeHabit: false,
  },
  {
    id: 'prop-dev-4',
    title: 'Read technical engineering design doc / RFC / Architecture chapter',
    category: 'Study',
    priority: 'medium',
    notes: 'Explore system design patterns, distributed consensus, or database indexing strategies.',
    estimatedPomodoros: 1,
    subtasks: [
      'Read 10-15 pages with active note taking',
      'Summarize key takeaways in personal knowledge base',
    ],
    track: 'Developer',
    canBeHabit: true,
    habitFrequency: 'daily',
  },
  {
    id: 'prop-dev-5',
    title: 'Deep uninterrupted coding session without Slack/email',
    category: 'Work',
    priority: 'high',
    notes: 'Enter flow state. Close notifications, set status to Focus Mode.',
    estimatedPomodoros: 3,
    subtasks: [
      'Close tabs & disable non-critical alerts',
      'Work strictly on the top technical milestone',
    ],
    track: 'Developer',
    canBeHabit: true,
    habitFrequency: 'weekdays',
  },

  // Student track
  {
    id: 'prop-stu-1',
    title: 'Review today’s lecture notes & generate flashcards (Anki)',
    category: 'Study',
    priority: 'high',
    notes: 'Consolidate raw class notes into concise question-and-answer spaced repetition cards.',
    estimatedPomodoros: 2,
    subtasks: [
      'Skim slides and lecture audio/notes',
      'Write 10-15 spaced repetition flashcards',
      'Test recall on key formulas/definitions',
    ],
    track: 'Student',
    canBeHabit: true,
    habitFrequency: 'weekdays',
  },
  {
    id: 'prop-stu-2',
    title: 'Complete 2 hours of focused assignment / coursework problem sets',
    category: 'Study',
    priority: 'high',
    notes: 'Break down complex homework questions systematically before consulting solutions.',
    estimatedPomodoros: 4,
    subtasks: [
      'Attempt problem set 1 independently',
      'Review textbook theory for stuck problems',
      'Format and double check final submission',
    ],
    track: 'Student',
    canBeHabit: false,
  },
  {
    id: 'prop-stu-3',
    title: 'Conduct active recall exam mock session (Past papers)',
    category: 'Study',
    priority: 'high',
    notes: 'Simulate timed exam environment without looking at notes.',
    estimatedPomodoros: 3,
    subtasks: [
      'Set timer for 45 minutes of strict closed-book practice',
      'Grade answers using marking scheme',
      'Log weak areas for revision',
    ],
    track: 'Student',
    canBeHabit: false,
  },
  {
    id: 'prop-stu-4',
    title: 'Read 2 academic research papers / chapters in primary field',
    category: 'Study',
    priority: 'medium',
    notes: 'Highlight methodologies, key findings, and open questions.',
    estimatedPomodoros: 2,
    track: 'Student',
    canBeHabit: true,
    habitFrequency: 'weekdays',
  },

  // Health & Fitness track
  {
    id: 'prop-fit-1',
    title: '45-minute gym strength workout or cardio run',
    category: 'Health/Fitness',
    priority: 'high',
    notes: 'Warm up thoroughly, focus on proper form and progressive overload or steady pacing.',
    estimatedPomodoros: 2,
    subtasks: [
      '5 min dynamic stretching & warm-up',
      'Main compound movements or interval cardio',
      'Cool-down stretches & hydration',
    ],
    track: 'Health/Fitness',
    canBeHabit: true,
    habitFrequency: 'daily',
  },
  {
    id: 'prop-fit-2',
    title: 'Hydration goal: Drink at least 2.5 Liters of pure water',
    category: 'Health/Fitness',
    priority: 'medium',
    notes: 'Keep a 1L water bottle filled beside desk throughout the workday.',
    estimatedPomodoros: 1,
    track: 'Health/Fitness',
    canBeHabit: true,
    habitFrequency: 'daily',
  },
  {
    id: 'prop-fit-3',
    title: '15-minute desk posture reset & mobility stretches',
    category: 'Health/Fitness',
    priority: 'medium',
    notes: 'Target hips, thoracic spine, neck, and wrist flexibility.',
    estimatedPomodoros: 1,
    subtasks: [
      'Doorway chest stretch & neck rolls',
      'Hip flexor couch stretch',
      'Wrist flexor & extensor stretch',
    ],
    track: 'Health/Fitness',
    canBeHabit: true,
    habitFrequency: 'daily',
  },
  {
    id: 'prop-fit-4',
    title: 'Prepare healthy balanced meals & hit daily protein target',
    category: 'Health/Fitness',
    priority: 'medium',
    notes: 'Clean whole foods, high fiber, and lean protein for sustained cognitive energy.',
    estimatedPomodoros: 2,
    track: 'Health/Fitness',
    canBeHabit: true,
    habitFrequency: 'daily',
  },

  // Productivity & General track
  {
    id: 'prop-prod-1',
    title: 'Inbox Zero & Slack triage: respond or schedule all inputs',
    category: 'Work',
    priority: 'medium',
    notes: '2-minute rule: if it takes under 2 mins do it now, otherwise convert to task or archive.',
    estimatedPomodoros: 1,
    subtasks: [
      'Archive or unsubscribe promotional noise',
      'Reply to critical blockers',
      'File follow-up tasks into daily board',
    ],
    track: 'Productivity',
    canBeHabit: true,
    habitFrequency: 'weekdays',
  },
  {
    id: 'prop-prod-2',
    title: 'Plan tomorrow’s Top 3 Most Important Tasks (MITs)',
    category: 'Personal',
    priority: 'high',
    notes: 'Clarify the 3 non-negotiables that will make tomorrow a definitive victory.',
    estimatedPomodoros: 1,
    subtasks: [
      'Review pending tasks from today',
      'Pick the 3 highest leverage items',
      'Block focus slots on calendar',
    ],
    track: 'Productivity',
    canBeHabit: true,
    habitFrequency: 'daily',
  },
  {
    id: 'prop-prod-3',
    title: 'Weekly review & retrospective: assess habits & adjust systems',
    category: 'Personal',
    priority: 'high',
    notes: 'Audit completion rates, habit streak trends, and recalibrate goals for next week.',
    estimatedPomodoros: 2,
    subtasks: [
      'Review habit consistency scores',
      'Clear digital clutter & desktop downloads',
      'Set primary OKRs for the coming week',
    ],
    track: 'Productivity',
    canBeHabit: false,
  },
  {
    id: 'prop-prod-4',
    title: 'Digital detox: zero screens 45 minutes before sleep',
    category: 'Personal',
    priority: 'medium',
    notes: 'Replace phone scrolling with physical book reading or mindful breathing.',
    estimatedPomodoros: 1,
    track: 'Productivity',
    canBeHabit: true,
    habitFrequency: 'daily',
  },
];
