import type { ProposedTask } from '../types';

export const PROPOSED_TASKS: ProposedTask[] = [
  // ==========================================
  // STUDENT & ACADEMIC TRACK (HỌC TẬP & SINH VIÊN)
  // ==========================================
  {
    id: 'prop-stu-1',
    title: 'Ôn tập slide bài giảng & tạo flashcard ôn bài (Anki / Quizlet)',
    category: 'Study',
    priority: 'high',
    notes: 'Tổng hợp các khái niệm chính, định nghĩa quan trọng và công thức cốt lõi sau mỗi buổi học trên trường.',
    estimatedPomodoros: 2,
    subtasks: [
      'Đọc lướt lại slide và ghi chú nhanh trong buổi học',
      'Tạo 15 thẻ Flashcard hỏi - đáp cho các định lý và khái niệm chính',
      'Tự kiểm tra độ ghi nhớ không nhìn tài liệu (Active Recall)',
    ],
    track: 'Student',
    canBeHabit: true,
    habitFrequency: 'weekdays',
  },
  {
    id: 'prop-stu-2',
    title: 'Làm bài tập về nhà môn chuyên ngành (Coursework & Problem Set)',
    category: 'Study',
    priority: 'high',
    notes: 'Tập trung giải độc lập các bài toán hóc búa trước khi đối chiếu đáp án.',
    estimatedPomodoros: 3,
    subtasks: [
      'Đọc kỹ yêu cầu đề bài và tóm tắt dữ kiện',
      'Giải bài tập phần 1 & 2 nháp sạch sẽ',
      'Kiểm tra lại kết quả tính toán và định dạng bản nộp bài',
    ],
    track: 'Student',
    canBeHabit: false,
  },
  {
    id: 'prop-stu-3',
    title: 'Học 20 từ vựng tiếng Anh học thuật (IELTS / TOEIC)',
    category: 'Study',
    priority: 'medium',
    notes: 'Học từ theo ngữ cảnh (collocations, ví dụ câu thực tế), phát âm chuẩn theo từ điển Cambridge/Oxford.',
    estimatedPomodoros: 1,
    subtasks: [
      'Ghi chép 20 từ mới kèm phiên âm và nghĩa ngữ cảnh',
      'Đặt 5 câu ví dụ áp dụng cho bài viết/nói',
      'Luyện phát âm chuẩn với ứng dụng từ điển',
    ],
    track: 'Student',
    canBeHabit: true,
    habitFrequency: 'daily',
  },
  {
    id: 'prop-stu-4',
    title: 'Luyện đề thi thử môn kiểm tra giữa kỳ / cuối kỳ (Mock Exam)',
    category: 'Study',
    priority: 'high',
    notes: 'Mô phỏng áp lực phòng thi: bấm giờ chính xác 60 phút, không tra cứu tài liệu.',
    estimatedPomodoros: 3,
    subtasks: [
      'In hoặc mở đề thi các năm trước',
      'Làm bài thi nghiêm túc trong đúng thời gian quy định',
      'Chấm điểm theo đáp án mẫu và ghi lại những câu sai để ôn bù',
    ],
    track: 'Student',
    canBeHabit: false,
  },
  {
    id: 'prop-stu-5',
    title: 'Đọc 15 trang giáo trình / tài liệu nghiên cứu chuyên sâu',
    category: 'Study',
    priority: 'medium',
    notes: 'Sử dụng phương pháp đọc tích cực (SQ3R) và ghi chú theo hệ thống Cornell.',
    estimatedPomodoros: 2,
    subtasks: [
      'Đọc lướt tiêu đề và câu mở đoạn để nắm ý chính',
      'Đọc kỹ và highlight các luận điểm then chốt',
      'Viết tóm tắt ngắn 1 đoạn văn bằng ngôn ngữ của chính mình',
    ],
    track: 'Student',
    canBeHabit: true,
    habitFrequency: 'weekdays',
  },
  {
    id: 'prop-stu-6',
    title: 'Họp nhóm đồ án / phân chia công việc bài tập lớn (Team Project)',
    category: 'Study',
    priority: 'high',
    notes: 'Xác định rõ ràng mục tiêu tuần này, deadline của từng thành viên và rủi ro trễ tiến độ.',
    estimatedPomodoros: 2,
    subtasks: [
      'Rà soát tiến độ từng phần công việc đã giao',
      'Thảo luận giải pháp tháo gỡ các vấn đề kỹ thuật / tài liệu',
      'Cập nhật tài liệu phân công nhiệm vụ và đặt lịch kiểm tra tiếp theo',
    ],
    track: 'Student',
    canBeHabit: false,
  },
  {
    id: 'prop-stu-7',
    title: 'Chuẩn bị trước bài học và đọc slide cho ca học ngày mai',
    category: 'Study',
    priority: 'medium',
    notes: 'Nắm trước dàn bài sẽ giúp tiếp thu bài giảng nhanh gấp đôi trên lớp.',
    estimatedPomodoros: 1,
    subtasks: [
      'Kiểm tra thời khóa biểu ca học ngày mai',
      'Tải slide và đọc trước chương bài học',
      'Ghi lại 2 câu hỏi còn thắc mắc để hỏi giảng viên trên lớp',
    ],
    track: 'Student',
    canBeHabit: true,
    habitFrequency: 'daily',
  },
  {
    id: 'prop-stu-8',
    title: 'Luyện nghe Podcast tiếng Anh khoa học / công nghệ 25 phút',
    category: 'Study',
    priority: 'low',
    notes: 'Luyện phản xạ nghe tự nhiên không cần dịch nhẩm trong đầu.',
    estimatedPomodoros: 1,
    track: 'Student',
    canBeHabit: true,
    habitFrequency: 'daily',
  },

  // ==========================================
  // DEVELOPER & TECH TRACK (LẬP TRÌNH & CÔNG NGHỆ)
  // ==========================================
  {
    id: 'prop-dev-1',
    title: 'Giải 1 bài thuật toán LeetCode (Binary Tree / Graph / Dynamic Programming)',
    category: 'Study',
    priority: 'high',
    notes: 'Phân tích kỹ độ phức tạp thời gian O(N) và không gian O(N) trước khi gõ code.',
    estimatedPomodoros: 2,
    subtasks: [
      'Đọc đề & vẽ sơ đồ mô phỏng các test case biên',
      'Hiện thực giải pháp cơ bản (Brute force)',
      'Tối ưu hóa cấu trúc dữ liệu và giải thuật',
    ],
    track: 'Developer',
    canBeHabit: true,
    habitFrequency: 'weekdays',
  },
  {
    id: 'prop-dev-2',
    title: 'Code 2 Pomodoro tính năng mới cho dự án cá nhân (Side Project)',
    category: 'Work',
    priority: 'high',
    notes: 'Tập trung sâu không mở mạng xã hội, chỉ mở IDE và tài liệu kỹ thuật liên quan.',
    estimatedPomodoros: 2,
    subtasks: [
      'Viết mã nguồn xử lý logic chính và định nghĩa TypeScript types',
      'Kiểm tra hiển thị giao diện UI trên các kích thước màn hình',
      'Commit mã nguồn với thông điệp rõ ràng theo chuẩn Conventional Commits',
    ],
    track: 'Developer',
    canBeHabit: true,
    habitFrequency: 'weekdays',
  },
  {
    id: 'prop-dev-3',
    title: 'Review Pull Request của nhóm & để lại nhận xét đóng góp',
    category: 'Work',
    priority: 'high',
    notes: 'Kiểm tra độ an toàn kiểu dữ liệu, bảo mật, clean code và test coverage.',
    estimatedPomodoros: 1,
    subtasks: [
      'Kéo branch về máy kiểm tra build thành công',
      'Đọc kỹ logic thay đổi và edge cases',
      'Góp ý xây dựng và phê duyệt PR',
    ],
    track: 'Developer',
    canBeHabit: false,
  },
  {
    id: 'prop-dev-4',
    title: 'Viết Unit Test & Integration Test cho các hàm xử lý dữ liệu',
    category: 'Work',
    priority: 'medium',
    notes: 'Đảm bảo tỷ lệ bao phủ kiểm thử >80% cho các module quan trọng.',
    estimatedPomodoros: 2,
    subtasks: [
      'Viết test cases cho luồng thành công (Happy Path)',
      'Viết test cases cho luồng lỗi và dữ liệu đầu vào không hợp lệ',
      'Chạy lệnh test và đảm bảo pass 100%',
    ],
    track: 'Developer',
    canBeHabit: false,
  },
  {
    id: 'prop-dev-5',
    title: 'Tìm hiểu tài liệu thiết kế hệ thống (System Design / Cloud Architecture)',
    category: 'Study',
    priority: 'medium',
    notes: 'Nghiên cứu về cơ chế Caching (Redis), Load Balancer, Microservices hoặc Database Sharding.',
    estimatedPomodoros: 2,
    track: 'Developer',
    canBeHabit: true,
    habitFrequency: 'weekdays',
  },

  // ==========================================
  // PRODUCTIVITY & DAILY ROUTINE (NĂNG SUẤT & KỶ LUẬT)
  // ==========================================
  {
    id: 'prop-prod-1',
    title: 'Lập danh sách 3 việc quan trọng nhất cần hoàn thành (Top 3 MITs)',
    category: 'Personal',
    priority: 'high',
    notes: 'Xác định rõ ràng 3 mục tiêu mang lại giá trị cao nhất trong ngày.',
    estimatedPomodoros: 1,
    subtasks: [
      'Xem lại các việc tồn đọng từ hôm qua',
      'Chọn ra 3 việc không thể bỏ lỡ trong ngày hôm nay',
      'Khóa khung giờ tập trung để thực hiện việc số 1 đầu tiên',
    ],
    track: 'Productivity',
    canBeHabit: true,
    habitFrequency: 'daily',
  },
  {
    id: 'prop-prod-2',
    title: 'Dọn sạch hộp thư Inbox Zero & sắp xếp lại tài liệu trên màn hình',
    category: 'Work',
    priority: 'medium',
    notes: 'Áp dụng quy tắc 2 phút: việc nào dưới 2 phút xử lý ngay, còn lại đưa vào lịch hoặc lưu trữ.',
    estimatedPomodoros: 1,
    subtasks: [
      'Xóa hoặc hủy đăng ký các email quảng cáo rác',
      'Phản hồi các thông báo quan trọng từ giảng viên / đồng nghiệp',
      'Dọn dẹp thư mục Downloads và Desktop ngăn nắp',
    ],
    track: 'Productivity',
    canBeHabit: true,
    habitFrequency: 'weekdays',
  },
  {
    id: 'prop-prod-3',
    title: 'Tổng kết ngày & viết nhật ký phản tư (Daily Reflection)',
    category: 'Personal',
    priority: 'high',
    notes: 'Dành 10 phút nhìn lại thành tựu, bài học rút ra và giải tỏa áp lực trước khi ngủ.',
    estimatedPomodoros: 1,
    subtasks: [
      'Đánh giá điểm số hiệu suất ngày (1-5 sao)',
      'Ghi lại ít nhất 2 điều bản thân tự hào đã làm được',
      'Lên kế hoạch ngắn gọn cho buổi sáng mai',
    ],
    track: 'Productivity',
    canBeHabit: true,
    habitFrequency: 'daily',
  },
  {
    id: 'prop-prod-4',
    title: 'Cắt giảm màn hình xanh (Digital Detox) 45 phút trước khi đi ngủ',
    category: 'Personal',
    priority: 'medium',
    notes: 'Để điện thoại xa giường, thay thế bằng đọc sách giấy hoặc nghe nhạc thư giãn.',
    estimatedPomodoros: 1,
    track: 'Productivity',
    canBeHabit: true,
    habitFrequency: 'daily',
  },
  {
    id: 'prop-prod-5',
    title: 'Đọc 10 trang sách phát triển tư duy / kỹ năng mềm',
    category: 'Personal',
    priority: 'low',
    notes: 'Tập trung vào Atomic Habits, Deep Work, hoặc kỹ năng giao tiếp.',
    estimatedPomodoros: 1,
    track: 'Productivity',
    canBeHabit: true,
    habitFrequency: 'daily',
  },

  // ==========================================
  // HEALTH & FITNESS TRACK (SỨC KHỎE & THỂ CHẤT)
  // ==========================================
  {
    id: 'prop-fit-1',
    title: 'Tập luyện thể thao 30-45 phút (Chạy bộ, gym hoặc cardio tại nhà)',
    category: 'Health/Fitness',
    priority: 'high',
    notes: 'Tăng cường tuần hoàn máu, giải phóng dopamine giúp não bộ tập trung học tập sắc bén hơn.',
    estimatedPomodoros: 2,
    subtasks: [
      '5 phút khởi động kỹ các khớp và cơ',
      '30 phút bài tập chính cường độ vừa phải',
      '5 phút giãn cơ tĩnh và uống nước bù khoáng',
    ],
    track: 'Health/Fitness',
    canBeHabit: true,
    habitFrequency: 'daily',
  },
  {
    id: 'prop-fit-2',
    title: 'Mục tiêu uống đủ 2 - 2.5 lít nước trong ngày',
    category: 'Health/Fitness',
    priority: 'medium',
    notes: 'Đặt bình nước 1L ngay bàn học và uống đều từng ngụm nhỏ suốt buổi học.',
    estimatedPomodoros: 1,
    track: 'Health/Fitness',
    canBeHabit: true,
    habitFrequency: 'daily',
  },
  {
    id: 'prop-fit-3',
    title: 'Giãn cơ cổ, vai, gáy và cột sống sau 2 ca học ngồi máy tính',
    category: 'Health/Fitness',
    priority: 'medium',
    notes: 'Ngăn ngừa thoái hóa đốt sống cổ và mỏi mắt khi học tập căng thẳng.',
    estimatedPomodoros: 1,
    subtasks: [
      'Bài tập xoay khớp cổ nhẹ nhàng 2 chiều',
      'Động tác ép ngực mở vai và kéo giãn cột sống',
      'Quy tắc 20-20-20: Nhìn ra xa 6 mét trong 20 giây cho mắt thư giãn',
    ],
    track: 'Health/Fitness',
    canBeHabit: true,
    habitFrequency: 'daily',
  },
  {
    id: 'prop-fit-4',
    title: 'Đi ngủ đúng giờ trước 23h30 để phục hồi năng lượng học tập',
    category: 'Health/Fitness',
    priority: 'high',
    notes: 'Ngủ đủ 7-8 tiếng là yếu tố số 1 giúp trí nhớ dài hạn củng cố kiến thức đã học.',
    estimatedPomodoros: 1,
    track: 'Health/Fitness',
    canBeHabit: true,
    habitFrequency: 'daily',
  },
];
